version: '3.6'
services:
  gitlab:
    image: 'gitlab/gitlab-ce:latest'
    container_name: gitlab
    restart: always
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://your-gitlab.com'
        letsencrypt['enable'] = false
        gitlab_rails['smtp_enable'] = true
        gitlab_rails['smtp_address'] = "smtp.gmail.com"
        gitlab_rails['smtp_port'] = 587
        gitlab_rails['smtp_user_name'] = "[your-email]@gmail.com"
        gitlab_rails['smtp_password'] = "[your-email-password]"
        gitlab_rails['smtp_domain'] = "gmail.com"
        gitlab_rails['smtp_authentication'] = "login"
        gitlab_rails['smtp_enable_starttls_auto'] = true
        gitlab_rails['smtp_tls'] = false
        gitlab_rails['gitlab_email_from'] = "[your-email]@gmail.com"
        gitlab_rails['gitlab_email_reply_to'] = "[`your-email`]@gmail.com"
        prometheus['monitor_kubernetes'] = false
        gitlab_rails['monitoring_whitelist'] = ['0.0.0.0/0', '::/0'] 
    ports:
      - '443:443'
      - '80:80'
    volumes:
      - './config:/etc/gitlab'
      - './logs:/var/log/gitlab'
      - './data:/var/opt/gitlab'
      - './backups:/var/opt/gitlab/backups'
    networks:
      - gitlab-network

networks:
  gitlab-network:

